apiVersion: v1
kind: Service
metadata:
  name: eval-php-min
  labels:
    app.kubernetes.io/name: eval-php-min
    app.kubernetes.io/instance: eval-php-min
    app.kubernetes.io/part-of: eval-php-min
spec:
  type: NodePort
  selector:
    app: eval-php-min
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
